//! Integration tests for hot-reload behavior under concurrent query load.
//!
//! These tests verify the atomicity and correctness guarantees of the
//! hot-reload subsystem (`ConfigStore` / `HotReloadManager` backed by
//! `ArcSwap`, and `HotSwapStore` backed by `ArcSwap`) when reloads and
//! hot-swaps happen concurrently with active "query load".
//!
//! The load is generated by spawning many tokio tasks that each perform
//! snapshot reads of the shared config / blocklist handle — the same
//! lock-free read path the DNS query handler uses. This keeps the tests
//! deterministic and network-independent while exercising the real
//! `ArcSwap` atomicity guarantees that matter for hot-reload correctness.
//!
//! ## Tests
//!
//! 1. `test_sighup_during_load` — reload config while queries are in
//!    flight; verify zero query failures.
//! 2. `test_blocklist_hot_swap_during_load` — hot-swap the blocklist
//!    store while lookups are in flight; verify old store serves until
//!    the swap completes and zero errors occur.
//! 3. `test_invalid_config_reload_during_load` — reload with an invalid
//!    config while queries are in flight; verify the old config remains
//!    active and zero errors occur.
//! 4. `test_rapid_sighup` — send many rapid reload signals in quick
//!    succession while under load; verify no panics or corruption.
//! 5. `test_arcswap_atomicity` — concurrent blocklist lookups + hot-swap
//!    with many iterations; verify no corrupted reads (ArcSwap atomicity).

mod common;

use common::{
    collect_load, compile_store, make_config_store, make_hot_reload_manager,
    make_hot_swap_store, spawn_blocklist_load, spawn_config_load, temp_dir,
    write_invalid_config, write_valid_config,
};
use dnshub::blocklist::{BlocklistEntry, BlocklistStore};
use std::sync::Arc;
use tokio::sync::Notify;

// ---------------------------------------------------------------------------
// Test 1: SIGHUP during active query load — zero query failures.
// ---------------------------------------------------------------------------

/// Start a `ConfigStore`, generate concurrent config snapshot reads
/// (simulating in-flight DNS queries), and trigger a config reload
/// (via `HotReloadManager::reload`, the same path SIGHUP uses) while
/// the reads are in flight. Verify that every read observes a valid,
/// consistent config and there are zero failures.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_sighup_during_load() {
    let dir = temp_dir("sighup-during-load");
    let config_path = dir.join("dnshub.toml");

    // Initial config: upstream at 1.1.1.1:53.
    write_valid_config(&config_path, "1.1.1.1:53", "initial");
    let store = make_config_store("1.1.1.1:53", "initial");
    let manager = make_hot_reload_manager(store.clone(), config_path.clone(), None);

    // Spawn load: 8 workers × 2000 reads = 16000 in-flight "queries".
    let handles = spawn_config_load(store.clone(), 8, 2000);

    // Mid-load, rewrite the config to a new upstream and reload.
    // The reload happens concurrently with the in-flight reads.
    tokio::task::yield_now().await;
    write_valid_config(&config_path, "9.9.9.9:53", "quad9");
    manager
        .reload()
        .expect("reload with a valid config should succeed");

    // Collect all load results.
    let result = collect_load(handles).await;

    // Every read must have observed a valid, consistent config.
    assert!(
        result.zero_failures(),
        "reload during load must not cause any query failures (got {} failures out of {} total)",
        result.failures,
        result.success + result.failures
    );
    assert_eq!(
        result.success, 16000,
        "all 16000 reads should succeed"
    );

    // After the reload, a fresh read sees the new upstream.
    let cfg = store.load_full();
    assert_eq!(cfg.upstreams[0].address, "9.9.9.9:53");
    assert_eq!(cfg.upstreams[0].name, "quad9");
}

// ---------------------------------------------------------------------------
// Test 2: Blocklist hot-swap during active query load — zero errors.
// ---------------------------------------------------------------------------

/// Start a `HotSwapStore` with an initial blocklist, generate concurrent
/// blocklist lookups (simulating in-flight DNS queries that consult the
/// blocklist), and trigger a hot-swap to a new store while lookups are
/// in flight. Verify that:
///
/// - Every lookup completes without error (the old store keeps serving
///   until the swap completes, then new lookups use the new store).
/// - After the swap, the new store is active and contains the new
///   entries.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_blocklist_hot_swap_during_load() {
    let dir = temp_dir("blocklist-hot-swap-during-load");

    // Initial store: 100 entries under "example.com".
    let hot_swap = make_hot_swap_store(&dir, 100, "example.com");

    // Spawn load: 8 workers × 2000 lookups = 16000 in-flight "queries".
    let handles = spawn_blocklist_load(hot_swap.clone(), 8, 2000, "example.com");

    // Mid-load, build a new store with 200 entries under "test.com" and
    // hot-swap it in. The swap happens concurrently with the in-flight
    // lookups.
    tokio::task::yield_now().await;
    let new_entries: Vec<BlocklistEntry> = (0..200)
        .map(|i| BlocklistEntry {
            domain: format!("domain{}.test.com", i),
            categories: 0,
            sources: 1,
        })
        .collect();
    let new_store = compile_store(&dir.join("updated"), new_entries);
    hot_swap.swap(new_store);

    // Collect all load results.
    let result = collect_load(handles).await;

    // Every lookup must have completed without error.
    assert!(
        result.zero_failures(),
        "hot-swap during load must not cause any lookup errors (got {} errors out of {} total)",
        result.failures,
        result.success + result.failures
    );
    assert_eq!(
        result.success, 16000,
        "all 16000 lookups should succeed"
    );

    // After the swap, the new store is active and contains the new entries.
    let store = hot_swap.load();
    assert_eq!(store.len().expect("len"), 200);
    assert!(store.is_blocked("domain0.test.com"));
    // The old entries are gone in the new store.
    assert!(!store.is_blocked("domain0.example.com"));
}

// ---------------------------------------------------------------------------
// Test 3: Invalid config reload during load — old config remains active.
// ---------------------------------------------------------------------------

/// Start a `ConfigStore` with a valid config, generate concurrent reads,
/// then overwrite the config file with an *invalid* config (no upstreams)
/// and trigger a reload. The reload must fail, the old config must remain
/// active, and every in-flight read must observe a valid config (zero
/// failures).
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_invalid_config_reload_during_load() {
    let dir = temp_dir("invalid-config-reload-during-load");
    let config_path = dir.join("dnshub.toml");

    // Initial valid config.
    write_valid_config(&config_path, "1.1.1.1:53", "initial");
    let store = make_config_store("1.1.1.1:53", "initial");
    let manager = make_hot_reload_manager(store.clone(), config_path.clone(), None);

    // Spawn load.
    let handles = spawn_config_load(store.clone(), 8, 2000);

    // Mid-load, overwrite with an invalid config and reload.
    tokio::task::yield_now().await;
    write_invalid_config(&config_path);
    let reload_result = manager.reload();
    assert!(
        reload_result.is_err(),
        "reload with an invalid config must fail"
    );

    // Collect all load results.
    let result = collect_load(handles).await;

    // Every read must have observed a valid config (the old one).
    assert!(
        result.zero_failures(),
        "invalid reload during load must not cause any query failures (got {} failures out of {} total)",
        result.failures,
        result.success + result.failures
    );
    assert_eq!(
        result.success, 16000,
        "all 16000 reads should succeed"
    );

    // After the failed reload, the old config is still active.
    let cfg = store.load_full();
    assert_eq!(
        cfg.upstreams[0].address,
        "1.1.1.1:53",
        "old config must be retained after a failed reload"
    );
    assert_eq!(cfg.upstreams[0].name, "initial");
}

// ---------------------------------------------------------------------------
// Test 4: Rapid SIGHUP signals — no panics or corruption.
// ---------------------------------------------------------------------------

/// Start a `ConfigStore`, generate concurrent reads, then trigger many
/// rapid reloads in quick succession (simulating 10 rapid SIGHUP
/// signals). Half the reloads use a valid config, half use an invalid
/// config. Verify that no panics occur, no corrupted reads are observed,
/// and the final active config is the last valid one.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_rapid_sighup() {
    let dir = temp_dir("rapid-sighup");
    let config_path = dir.join("dnshub.toml");

    // Initial valid config.
    write_valid_config(&config_path, "1.1.1.1:53", "initial");
    let store = make_config_store("1.1.1.1:53", "initial");
    let manager = make_hot_reload_manager(store.clone(), config_path.clone(), None);

    // Spawn load: 8 workers × 3000 reads = 24000 in-flight "queries".
    let handles = spawn_config_load(store.clone(), 8, 3000);

    // Fire 10 rapid reloads, alternating valid and invalid configs.
    // Each reload runs on the current thread (the SIGHUP handler path),
    // so they are serialized relative to each other but concurrent with
    // the in-flight reads.
    tokio::task::yield_now().await;
    for i in 0..10u32 {
        if i % 2 == 0 {
            // Valid config with a new upstream address.
            let addr = format!("10.0.0.{}:53", i + 1);
            write_valid_config(&config_path, &addr, &format!("rapid-{i}"));
        } else {
            // Invalid config (no upstreams).
            write_invalid_config(&config_path);
        }
        // reload() is the exact path the SIGHUP handler calls. Errors
        // (from invalid configs) are expected and must not panic.
        let _ = manager.reload();
    }

    // Collect all load results.
    let result = collect_load(handles).await;

    // No panics, no corrupted reads.
    assert!(
        result.zero_failures(),
        "rapid SIGHUP must not cause any query failures (got {} failures out of {} total)",
        result.failures,
        result.success + result.failures
    );
    assert_eq!(
        result.success, 24000,
        "all 24000 reads should succeed"
    );

    // The final active config is the last *valid* one. The last reload
    // (i=9, odd) was invalid, so the active config is from i=8 (the last
    // even/valid reload): 10.0.0.9:53, name "rapid-8".
    let cfg = store.load_full();
    assert_eq!(cfg.upstreams[0].address, "10.0.0.9:53");
    assert_eq!(cfg.upstreams[0].name, "rapid-8");
}

// ---------------------------------------------------------------------------
// Test 5: ArcSwap atomicity under concurrent access — no corrupted reads.
// ---------------------------------------------------------------------------

/// Verify `ArcSwap` atomicity for the blocklist `HotSwapStore` under
/// heavy concurrent access. Spawn many reader tasks that continuously
/// load the active store and perform lookups, while a writer repeatedly
/// hot-swaps in new stores with different entry counts. After many
/// iterations, verify:
///
/// - Zero lookup errors (no corrupted reads).
/// - Every `load()` returns a store whose `len()` is one of the known
///   sizes (50, 100, or 200) — never a partial or torn value.
/// - The final active store is the last swapped one.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_arcswap_atomicity() {
    let dir = temp_dir("arcswap-atomicity");

    // Initial store: 50 entries under "atomic.test".
    let hot_swap = make_hot_swap_store(&dir, 50, "atomic.test");

    // Spawn 12 readers × 4000 lookups = 48000 concurrent reads.
    let reader_handles = spawn_blocklist_load(hot_swap.clone(), 12, 4000, "atomic.test");

    // Concurrently perform 20 hot-swaps with varying entry counts.
    // Each swap builds a fresh store and atomically replaces the active
    // one. Readers that loaded the old store before the swap continue
    // using it; new readers get the new store.
    let hot_swap_writer = hot_swap.clone();
    let writer_handle: tokio::task::JoinHandle<()> = tokio::spawn(async move {
        let sizes = [50, 100, 200, 100, 50, 200];
        for (i, &size) in sizes.iter().cycle().take(20).enumerate() {
            let entries: Vec<BlocklistEntry> = (0..size)
                .map(|j| BlocklistEntry {
                    domain: format!("domain{j}.atomic.test"),
                    categories: 0,
                    sources: 1,
                })
                .collect();
            // Build into a unique subdirectory per swap to avoid LMDB
            // env collisions on the same path (LMDB refuses to open an
            // environment that is already open in this process).
            let swap_dir = dir.join(format!("swap-{i}"));
            let new_store = compile_store(&swap_dir, entries);
            hot_swap_writer.swap(new_store);
            // Yield so readers interleave with swaps.
            tokio::task::yield_now().await;
        }
    });

    // Drive a separate set of "len probes" that verify every loaded
    // store reports one of the known sizes (never a torn value).
    let hot_swap_probes = hot_swap.clone();
    let probe_handle: tokio::task::JoinHandle<u64> = tokio::spawn(async move {
        let mut bad_lens = 0u64;
        for _ in 0..5000 {
            let store = hot_swap_probes.load();
            let len = store.len().unwrap_or(0);
            // The known sizes are 50, 100, 200. Any other value would
            // indicate a torn read from ArcSwap (which should be
            // impossible, but we verify it).
            if !matches!(len, 0 | 50 | 100 | 200) {
                bad_lens += 1;
            }
            tokio::task::yield_now().await;
        }
        bad_lens
    });

    // Wait for the writer and probes to finish.
    writer_handle.await.expect("writer task panicked");
    let bad_lens = probe_handle.await.expect("probe task panicked");

    // Collect reader results.
    let result = collect_load(reader_handles).await;

    // Zero lookup errors.
    assert!(
        result.zero_failures(),
        "ArcSwap must provide atomic reads: no lookup errors (got {} errors out of {} total)",
        result.failures,
        result.success + result.failures
    );
    assert_eq!(
        result.success, 48000,
        "all 48000 lookups should succeed"
    );

    // Zero torn length reads.
    assert_eq!(
        bad_lens, 0,
        "ArcSwap must not produce torn reads: every len() must be a known size"
    );

    // The final active store is the last swapped one. The writer did 20
    // swaps cycling through [50, 100, 200, 100, 50, 200]. The last
    // iteration is index 19; 19 % 6 = 1, so sizes[1] = 100.
    let final_store = hot_swap.load();
    assert_eq!(
        final_store.len().expect("final len"),
        100,
        "final store should be the last swapped one (100 entries)"
    );
}

// ---------------------------------------------------------------------------
// Extra: verify the blocklist refresh Notify fires on a successful reload
// while under load. This confirms the SIGHUP → blocklist daemon trigger
// path is not broken by concurrent access.
// ---------------------------------------------------------------------------

/// Reload the config while under load and verify the blocklist refresh
/// `Notify` fires (so the blocklist daemon would be triggered). This
/// exercises the `HotReloadManager::reload` → `Notify::notify_one` path
/// concurrently with config reads.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_reload_triggers_blocklist_refresh_under_load() {
    let dir = temp_dir("reload-notify-under-load");
    let config_path = dir.join("dnshub.toml");

    write_valid_config(&config_path, "1.1.1.1:53", "initial");
    let store = make_config_store("1.1.1.1:53", "initial");

    let notify = Arc::new(Notify::new());
    // Register a waiter *before* spawning the load so we observe the
    // notification even if it fires before we await. The waiter borrows
    // `notify`; pass a clone to the manager so the original stays alive
    // for the waiter (both point at the same `Notify`).
    let waiter = notify.notified();
    let notify_for_manager = notify.clone();
    let manager =
        make_hot_reload_manager(store.clone(), config_path.clone(), Some(notify_for_manager));

    // Spawn load.
    let handles = spawn_config_load(store.clone(), 4, 500);

    // Reload — should fire the notify.
    manager.reload().expect("valid reload should succeed");

    // The waiter should resolve immediately (notify_one was called).
    tokio::time::timeout(std::time::Duration::from_secs(2), waiter)
        .await
        .expect("blocklist refresh notify should fire within 2s");

    // Collect load results — no failures.
    let result = collect_load(handles).await;
    assert!(
        result.zero_failures(),
        "reload + notify under load must not cause failures"
    );
}

// ---------------------------------------------------------------------------
// Extra: verify that a held config snapshot remains stable across a swap.
// This is the core ArcSwap guarantee: a reader holding an Arc<DnshubConfig>
// continues to see the old config even after a swap publishes a new one.
// ---------------------------------------------------------------------------

/// Hold a config snapshot, swap in a new config, and verify the held
/// snapshot still points at the old config while a fresh load sees the
/// new one. Run this under concurrent load to stress the ArcSwap ref
/// counting.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_held_snapshot_stable_across_swap_under_load() {
    let dir = temp_dir("held-snapshot-under-load");
    let config_path = dir.join("dnshub.toml");

    write_valid_config(&config_path, "1.1.1.1:53", "initial");
    let store = make_config_store("1.1.1.1:53", "initial");
    let manager = make_hot_reload_manager(store.clone(), config_path.clone(), None);

    // Hold a snapshot of the initial config.
    let held = store.load_full();
    assert_eq!(held.upstreams[0].address, "1.1.1.1:53");

    // Spawn load.
    let handles = spawn_config_load(store.clone(), 4, 500);

    // Swap in a new config.
    write_valid_config(&config_path, "8.8.8.8:53", "google");
    manager.reload().expect("valid reload should succeed");

    // Collect load.
    let result = collect_load(handles).await;
    assert!(result.zero_failures(), "no failures during swap under load");

    // The held snapshot still points at the old config.
    assert_eq!(
        held.upstreams[0].address,
        "1.1.1.1:53",
        "held snapshot must remain stable across a swap"
    );

    // A fresh load sees the new config.
    let fresh = store.load_full();
    assert_eq!(fresh.upstreams[0].address, "8.8.8.8:53");
    assert_eq!(fresh.upstreams[0].name, "google");
}

// ---------------------------------------------------------------------------
// Extra: verify the blocklist hot-swap `swap_database` path (which builds
// in a temp dir then swaps) works under concurrent lookups.
// ---------------------------------------------------------------------------

/// Exercise `HotSwapStore::swap_database` (the build-then-swap path used
/// by the blocklist daemon) while concurrent lookups are in flight.
/// Verify zero errors and the new store is active afterwards.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn test_swap_database_during_load() {
    let dir = temp_dir("swap-database-during-load");
    let hot_swap = make_hot_swap_store(&dir, 50, "swapdb.test");

    // Spawn lookups.
    let handles = spawn_blocklist_load(hot_swap.clone(), 8, 1000, "swapdb.test");

    // Build a new database via swap_database (build_fn + atomic swap).
    let entries: Vec<BlocklistEntry> = (0..150)
        .map(|i| BlocklistEntry {
            domain: format!("domain{}.swapdb.test", i),
            categories: 0,
            sources: 1,
        })
        .collect();
    let entries_for_closure = entries.clone();
    let swap_result = hot_swap.swap_database(|temp_path| {
        Ok(compile_store(temp_path, entries_for_closure))
    });
    assert!(swap_result.is_ok(), "swap_database should succeed");

    // Collect lookups.
    let result = collect_load(handles).await;
    assert!(
        result.zero_failures(),
        "swap_database during load must not cause lookup errors (got {} errors)",
        result.failures
    );
    assert_eq!(result.success, 8000);

    // New store is active with 150 entries.
    let store = hot_swap.load();
    assert_eq!(store.len().expect("len"), 150);
    assert!(store.is_blocked("domain0.swapdb.test"));
}
